# Generated by Django 5.2.8 on 2025-11-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(default='usuario', max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Perfil/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
